### PR TITLE
add nix

### PR DESCRIPTION
**Pull request by chessai**
- add nix
- github: 0.22 -> 0.21
- add binary wrapper, so you dont have to install poppler_utils separately

### CODE REVIEW

**Comment by chessai** [comment]
example:

```
nix-build && ./result/bin/fermatslastmargin
```

should Just Work

**Review by shapr — APPROVED** [review]
lgtm

**Comment by GTrunSec** [comment]
nix-build failed by Github version. I just modified  0.21 to 0.22. then cabal update and cabal run. passed  on nix-shell

**Comment by chessai** [comment]
Do you mean cabal and not cargo?

Also, i'm really confused. This built (using nix-build and cabal v2-build)
for me with github 0.21, but not 0.22. How are you building?

**Comment by GTrunSec** [comment]
sorry about that, cabal not cargo. 
nix-shell info:

<details>

```
Preprocessing library for fermatslastmargin-0.1.0.0..                                                                          [947/1977]
Building library for fermatslastmargin-0.1.0.0..
[1 of 2] Compiling Lib.Github       ( src/Lib/Github.hs, dist/build/Lib/Github.o )
[2 of 2] Compiling Lib              ( src/Lib.hs, dist/build/Lib.o ) 

src/Lib.hs:(362,14)-(365,23): error:
    • Couldn't match expected type ‘ValueSpec GithubConfig’
                  with actual type ‘ValueSpecs GithubConfig’
    • In the expression:
        sectionsSpec "github"
          $ do username <- reqSection "username" "GitHub username"
               oauth <- reqSection "oauth" "OAuth Token for GitHub"
               return GC {..}
      In an equation for ‘githubSpec’:
          githubSpec
            = sectionsSpec "github"
                $ do username <- reqSection "username" "GitHub username"
                     oauth <- reqSection "oauth" "OAuth Token for GitHub"
                     return GC {..}
    |
362 | githubSpec = sectionsSpec "github" $
    |              ^^^^^^^^^^^^^^^^^^^^^^^...

builder for '/nix/store/v1x41m8739am6sk7rg9wpvyxw17vks0i-fermatslastmargin-0.1.0.0.drv' failed with exit code 1
error: build of '/nix/store/v1x41m8739am6sk7rg9wpvyxw17vks0i-fermatslastmargin-0.1.0.0.drv' failed
```
</details>

I knew if you specified nixpkgs rev which was on source.json. It will not pass on the current master rev. this is my nixpkgs rev https://github.com/GTrunSec/nixpkgs. and modified commit https://github.com/GTrunSec/fermatslastmargin/commit/3529147fe7b76e27e63dabe529343bd5cabb8ef7
`I just passed the test using nix-shell not nix-build`



<details>

```
nixos :: ~/project/fermatslastmargin ‹master*›                                                                                          
» nix-shell --command "cabal update && cabal run"                                                                                       
Downloading the latest package list from hackage.haskell.org                                                                            
To revert to previous state run:                                                                                                        
    cabal v2-update 'hackage.haskell.org,2019-12-04T05:45:03Z'                                                                          
Resolving dependencies...                                                                                                               
Build profile: -w ghc-8.6.4 -O1                                                                                                         
In order, the following will be built (use -v for more details):                                                                        
 - fermatslastmargin-0.1.0.0 (lib) (configuration changed)                                                                              
 - fermatslastmargin-0.1.0.0 (exe:fermatslastmargin) (first run)                                                                        
Configuring library for fermatslastmargin-0.1.0.0..                                                                                     
Preprocessing library for fermatslastmargin-0.1.0.0..                                                                                   
Building library for fermatslastmargin-0.1.0.0..                                                                                        
[1 of 2] Compiling Lib.Github       ( src/Lib/Github.hs, /home/gtrun/project/fermatslastmargin/dist-newstyle/build/x86_64-linux/ghc-8.6.
4/fermatslastmargin-0.1.0.0/build/Lib/Github.o ) [Network.HTTP.Client changed]                                                          
[2 of 2] Compiling Lib              ( src/Lib.hs, /home/gtrun/project/fermatslastmargin/dist-newstyle/build/x86_64-linux/ghc-8.6.4/ferma
tslastmargin-0.1.0.0/build/Lib.o )  

```
</details>

**Comment by chessai** [comment]
Are you on master, or this branch?

Because on this branch, i made the ValueSpec change, and moved github to
0.21. @shapr reverted the change to ValueSpec on master, so it makes sense
that the build would fail now, but this branch, when merged, did build. I
will probably just move away from the stable nixpkgs to get the newer
github.

**Comment by GTrunSec** [comment]
sorry to reply to your answer later. I have seen you commit that changed ValueSpec to ValueSpecs.  thank you let me know that. I think you can put the patch on nix config which has your changed original code.

**Pull request merged**
